DROP TABLE IF EXISTS TRANSACTION_RECORD;
DROP TABLE IF EXISTS CUSTOMER;

CREATE TABLE CUSTOMER (
  CUS_UNAME VARCHAR(32) PRIMARY KEY,
  CUS_PASSWD_HASH VARCHAR(255) NOT NULL,
  CUS_BALANCE DECIMAL(15, 2) NOT NULL DEFAULT 0.00
);

CREATE TABLE TRANSACTION_RECORD (
  TXN_ID INT AUTO_INCREMENT PRIMARY KEY,
  CUS_ID_SOURCE VARCHAR(32),
  CUS_ID_DEST VARCHAR(32),
  TXN_AMOUNT DECIMAL(15, 2) NOT NULL,
  TXN_DATETIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (CUS_ID_SOURCE) REFERENCES CUSTOMER (CUS_UNAME),
  FOREIGN KEY (CUS_ID_DEST) REFERENCES CUSTOMER (CUS_UNAME)
);