CREATE DATABASE IF NOT EXISTS bankdb;
USE bankdb;


DROP TABLE IF EXISTS transaction_record;
DROP TABLE IF EXISTS customer;

-- Customer table
CREATE TABLE customer (
    CUS_UNAME VARCHAR(32) PRIMARY KEY,
    CUS_PASSWD_HASH VARCHAR(255),
    CUS_BALANCE DECIMAL(15 , 2 )
);

-- Transaction record table
CREATE TABLE transaction_record (
    TXN_ID INT PRIMARY KEY AUTO_INCREMENT,
    CUS_ID_SOURCE VARCHAR(32) NULL,
    CUS_ID_DEST VARCHAR(32) NULL,
    TXN_AMOUNT DECIMAL(15 , 2 ),
    TXN_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (CUS_ID_SOURCE)
        REFERENCES customer (CUS_UNAME),
    FOREIGN KEY (CUS_ID_DEST)
        REFERENCES customer (CUS_UNAME)
);